manageSport/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('worldCupShop.urls')),
    path('admin/', admin.site.urls),
]

worldCupShop/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

from worldCupShop import views
from manageSport import settings

app_name = 'worldCupShop'
urlpatterns = [
                  path('', views.index, name='index'),
                  path('<int:pk>/', views.ProgrammeAddView.as_view(), name='detail'),
                  path('accounts/login', views.MyLoginView.as_view(), name='login'),
                  path('accounts/logout', views.MyLogoutView.as_view(), name='logout'),
                  path('accounts/register', views.register, name='register'),
                  path('accounts/profil_edit', views.ProfilEditView.as_view(), name='profil_edit'),
                  path('programmes/', views.ProgrammeListView.as_view(), name='programmes'),
                  path('programmes/delete_programme', views.ProgrammeDeleteView.as_view(), name='delete_programme'),
                  path('programmes/exercices/get_exercices_by_zone_muscles', views.GetExercicesByZoneMusclesView.as_view(), name='get_exercices_by_zone_muscles'),
                  path('programmes/exercices/add_exercice_line', views.AddExerciceLineView.as_view(), name='add_exercice_line'),
                  path('programmes/add', views.ProgrammeAddView.as_view(), name='programmes_add'),
                  path('programmes/planning', views.PlanningGet.as_view(), name='programme_planning'),
                  path('programmes/add_programme_to_calendar', views.ProgrammeCalendarAdd.as_view(), name='add_programme_to_calendar'),
                  path('programmes/delete_exercice_line', views.ExerciceLineDelete.as_view(), name='delete_exercice_line'),
                  path('programmes/all_exercices', views.ExerciceRetrieval.as_view(), name='get_all_exercices'),
                  path('programmes/delete_entrainement', views.EntrainementDelete.as_view(), name='delete_entrainement_from_calendar'),
                  path('programmes/mes_statistiques', views.MyStatsView.as_view(), name='my_stats'),
                  path('programmes/suggerer_nom', views.SuggestionExerciceAdd.as_view(), name='add_suggestion_exercice'),
                  path('programmes/<int:pk>/', views.ProgrammeView.as_view(), name='programmes_detail'),
                  path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
                  path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldCupShop/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Programme(models.Model):
    label = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    thumbnail = models.ImageField(upload_to="exercises", blank=True, null=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=1)
    status = models.CharField(max_length=50, default="private")
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.label


class Exercice(models.Model):
    label = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    programme = models.ManyToManyField(Programme)
    thumbnail = models.ImageField(upload_to="exercises", blank=True, null=True)

    def __str__(self):
        return self.label


class ExerciceImported(models.Model):
    partieCorps = models.CharField(max_length=100)
    equipement = models.CharField(max_length=100)
    gifUrl = models.CharField(max_length=200)
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    zoneMuscleEnglish = models.CharField(max_length=100)
    nom = models.CharField(max_length=100)
    zoneMuscle = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ExerciceLine(models.Model):
    label = models.CharField(max_length=100)
    nbRepetition = models.IntegerField(default=0)
    nbSerie = models.IntegerField(default=0)
    exercice = models.ForeignKey(ExerciceImported, on_delete=models.CASCADE)
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE, null=True)
    order = models.IntegerField(default=1000)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.label


class Fiche(models.Model):
    label = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    filename = models.CharField(max_length=200)

    def __str__(self):
        return self.label


class SuggestionNom(models.Model):
    nom_suggere = models.CharField(max_length=100)
    exercice = models.ForeignKey(ExerciceImported, on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=1)


class ExerciceLineRepetition(models.Model):
    exerciceLine = models.ForeignKey(ExerciceLine, on_delete=models.CASCADE)
    serieNumber = models.IntegerField(default=0)
    nbRepetition = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)


class Entrainement(models.Model):
    label = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE)
    date = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.label


# class User(models.Model):

worldCupShop/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    pass


# formulaire d'ajout de programme
class AddProgrammeForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label

    label = forms.CharField(label='Titre', max_length=100, required=True)
    description = forms.CharField(widget=forms.Textarea, label='Description', max_length=1000)
    thumbnail = forms.ImageField(label='Image (facultatif)', required=False)


# formulaire d'ajout de ligne d'exercice
class AddExerciceLineForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label

    # exercice = forms.CharField(label='Exercice', max_length=100)
    label = forms.CharField(label='Titre', max_length=100)
    nbSerie = forms.IntegerField(label='Nombre de série')
    # nbRepetition = forms.IntegerField(label='Nombre de répétition')


class UserPersonalizeForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label

    first_name = forms.CharField(label='Prénom', max_length=100, required=False)
    last_name = forms.CharField(label='Nom', max_length=100, required=False)
    username = forms.CharField(label='Nom d\'utilisateur', max_length=100, required=True)
    email = forms.EmailField(label='Email', max_length=100, required=True)

worldCupShop/templates/worldCupShop/add_programme.html
{% extends 'worldCupShop/base.html' %}
{% load static %}


{% block breadcrumb %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Programmes</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Mon Profil</a></li>
                        <li class="breadcrumb-item active">Mes Programmes</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
{% endblock %}
{% block content %}
    <div class="row mb-3 justify-content-end m-1">
        <div class="btn-group">
            <button type="button" class="btn btn-info">Action</button>
            <button type="button" class="btn btn-info dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right" role="menu" style="">
                <a class="dropdown-item" href="#">Ajouter un programme</a>
                <a class="dropdown-item" href="#">Modifier l'ordre des programmes</a>
                <a class="dropdown-item" href="#">Something else here</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Separated link</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Programme</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    {% comment %}<div class="form-group">
                <label for="inputName">Nom du programme</label>
                <input type="text" id="inputName" class="form-control">
              </div>
              <div class="form-group">
                <label for="inputDescription">Description du programme</label>
                <textarea id="inputDescription" class="form-control" rows="4"></textarea>
              </div>
              <div class="form-group">
                <label for="inputStatus">Status</label>
                <select id="inputStatus" class="form-control custom-select">
                  <option selected disabled>Select one</option>
                  <option>On Hold</option>
                  <option>Canceled</option>
                  <option>Success</option>
                </select>
              </div>
              <div class="form-group">
                <label for="inputClientCompany">Client Company</label>
                <input type="text" id="inputClientCompany" class="form-control">
              </div>
              <div class="form-group">
                <label for="inputProjectLeader">Project Leader</label>
                <input type="text" id="inputProjectLeader" class="form-control">
              </div>{% endcomment %}
                    <form enctype="multipart/form-data" action="{% url 'worldCupShop:programmes_add' %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Ajouter un programme</button>
                        <a href="{% url 'worldCupShop:programmes' %}" class="btn btn-danger float-right">Retour</a>
                    </form>

                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>



    {% comment %}<div class="col-md-6">
          <div class="card card-secondary">
            <div class="card-header">
              <h3 class="card-title">Budget</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="card-body">
              <div class="form-group">
                <label for="inputEstimatedBudget">Estimated budget</label>
                <input type="number" id="inputEstimatedBudget" class="form-control">
              </div>
              <div class="form-group">
                <label for="inputSpentBudget">Total amount spent</label>
                <input type="number" id="inputSpentBudget" class="form-control">
              </div>
              <div class="form-group">
                <label for="inputEstimatedDuration">Estimated project duration</label>
                <input type="number" id="inputEstimatedDuration" class="form-control">
              </div>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>{% endcomment %}

    <script>
        $('.card-programme').on('click', function () {
            self = $(this)
            console.log(self.find('span').html());
        })

    </script>
{% endblock %}

worldCupShop/templates/worldCupShop/dashboard_sport.html
{% extends 'worldCupShop/base.html' %}
{% load static %}

{% block content %}
    <div class="mb-4">
        <div class="btn-group float-right">
            <button type="button" class="btn btn-info">Action</button>
            <button type="button" class="btn btn-info dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right" role="menu" style="">
                <a class="dropdown-item" href="{% url 'worldCupShop:programmes_add' %}">Ajouter un programme</a>
                {% comment %}<a class="dropdown-item" href="#">Modifier l'ordre des programmes</a>
                <a class="dropdown-item" href="#">Something else here</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Separated link</a>{% endcomment %}
            </div>
        </div>
        <h2 class="justify-content-center">Votre dashboard sportif</h2>

    </div>
    <div class="row">
        {% for programme in programmes %}

            <div class="col-md-12 col-lg-6 col-xl-4 border-1">
                <div class="card mb-2 bg-gradient-dark">
                    <a href="{% url 'worldCupShop:programmes_detail' programme.id %}" class="card-programme">
                        {% if programme.thumbnail %}
                            <img class="card-img-top" src="/media/{{ programme.thumbnail }}" alt="Dist Photo 1">
                        {% else %}
                            <img class="card-img-top" src="/media/exercises/fitness_exercices_profil.jpg" alt="Dist Photo 1">
                        {% endif %}
                        <div class="card-img-overlay d-flex flex-column justify-content-end">
                            <h5 class="card-title text-primary text-white">{{ programme.label }}</h5>
                            <p class="card-text text-white pb-2 pt-1">{{ programme.description }}</p>
                            <a href="#" class="text-white">Last update 2 mins ago</a>
                        </div>
                    </a>
                </div>
                <button type="button" class="btn btn-danger btn-sm float-right delete_programme" data-id="{{ programme.id }}">
                    <i class="fa fa-trash"></i>
                </button>
            </div>
        {% endfor %}
    </div>

    {% block script %}
        <script>
            $(document).ready(function () {
                $('.card-programme').on('click', function () {
                    self = $(this)
                    console.log(self.find('span').html());
                })

                $('.delete_programme').on('click', function () {
                    console.log('delete');
                    self = $(this);

                    $('#delete-modal').modal('show');

                    $('.confirm_delete').on('click', function () {
                        $('#delete-modal').modal('hide');

                        $.ajax({
                            url: "{% url 'worldCupShop:delete_programme' %}",
                            type: 'POST',
                            data: {
                                csrfmiddlewaretoken: "{{ csrf_token }}",
                                'programme_id': self.data('id'),
                            },
                            success: function (data) {
                                $(document).Toasts('create', {
                                    class: 'bg-success',
                                    title: 'Suppression du programme',
                                    body: 'La suppression du programme a bien été faite.'
                                })
                                setTimeout(function () {
                                    location.reload();
                                }, 2000);
                                location.reload();
                            }
                        })

                    })
                })
            });
        </script>
    {% endblock %}
{% endblock %}

worldCupShop/templates/worldCupShop/detail.html
{% extends 'worldCupShop/base.delete.html' %}

{% block content %}

    <form action="{% url 'worldCupShop:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
{% endblock %}

worldCupShop/templates/worldCupShop/index.html
{% extends 'worldCupShop/base.html' %}

{% block content %}
    <div class="text-primary text-center">
    Voici Une liste des fonctionnalitées disponibles actuellement :
        <ul>
            <li><span class="text-dark">Consulter les différentes pages liées à la nutrition.</span></li>
            <li><span class="text-dark">Consulter son programme de sport.</span></li>
        </ul>
    </div>
<script>
</script>
{% endblock %}

worldCupShop/templates/worldCupShop/mon_profil.html
{% extends 'worldCupShop/base.html' %}
{% load static %}


{% block breadcrumb %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Programmes</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Mon Profil</a></li>
                        <li class="breadcrumb-item active">Mes Programmes</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
{% endblock %}
{% block content %}
    <div class="row mb-3 justify-content-end m-1">
        <div class="btn-group">
            <button type="button" class="btn btn-info">Action</button>
            <button type="button" class="btn btn-info dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right" role="menu" style="">
                <a class="dropdown-item" href="#">Ajouter un programme</a>
                <a class="dropdown-item" href="#">Modifier l'ordre des programmes</a>
                <a class="dropdown-item" href="#">Something else here</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Separated link</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 m-auto">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Mon profil</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <form enctype="multipart/form-data" action="{% url 'worldCupShop:profil_edit' %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                        <a href="{% url 'worldCupShop:index' %}" class="btn btn-danger float-right">Retour</a>
                    </form>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $('.card-body p').css({"display": "flex", "flex-direction": "column"});
        $('#id_first_name').val('{{ user.first_name }}');
        $('#id_last_name').val('{{ user.last_name }}');
        $('#id_username').val('{{ user.username }}');
        $('#id_email').val('{{ user.email }}');
    </script>
{% endblock %}

worldCupShop/templates/worldCupShop/results.html
{% extends 'worldCupShop/base.delete.html' %}

{% block content %}
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'worldCupShop:detail' question.id %}">Vote again?</a>
{% endblock %}